### PR TITLE
[Feature] Support for enterprise Github repository

### PR DESCRIPTION
**Pull request by nlunets**
Add an extra parameters in the tsd.json file to support specifying the url to your github host.

Parameter name is githubHost and by default will point to github.com (so no change to current behavior).

If an enterprise github url is specified instead then the url for requests will be adapted to follow the scheme of enterprise github.

### CODE REVIEW

**Comment by nlunets** [comment]
I'm not entirely sure why the travis CI build is failing on those API calls, the appveyor one does the same and works :/

**Comment by Diullei** [comment]
Very nice! 

The tests has been fixed! I'll integrate this PR today!

thanks!

**Comment by nlunets** [comment]
Well thank you !

**Comment by nlunets** [comment]
Do you think you could publish a new version on npm with this code ? :)

**Comment by Diullei** [comment]
Hi @nlunets! We'll add more features/fixes before next release. 

Thanks for this contribution :)

**Pull request merged**
