### PR TITLE
Use GITHUB_TOKEN environment variable if possible for github authorization

### LINKED ISSUE #157: tsd rate limiting token in Travis builds
Is there an easy way to set up a rate limit token on Travis? From the documentation, it seems the token must be in a .tsdrc file, which would have to be committed into the source repository, and therefore publicly visible. It should be set in an ENV variable, which could then be configured as a Travis secure variable. But the TSD documentation does not specify that is possible.

### PR DESCRIPTION
**Pull request by BertHartm**
Resolves #157

### CODE REVIEW

**Comment by blakeembrey** [comment]
I'm thinking we should use `TSD_GITHUB_TOKEN` for a little name spacing. What do you think?

**Comment by BertHartm** [comment]
I considered this, but I'm thinking for most of my workflows, I'd want to use the same token for the whole process.
To put it another way, I can't imagine a scenario where I'd have GITHUB_TOKEN already set for another process and not want it to be the same token and automatically picked up.
I'm open to changing it if people feel otherwise.

**Comment by blakeembrey** [comment]
I am open to merging a version with the prefix. I don't think using a general token makes sense since it promotes re-using tokens across applications, these tools will contribute to the same rate limit and the GitHub UI and API is friendly enough to allow people to easily create named tokens for applications.

**Comment by BertHartm** [comment]
Fair enough. Changed and updated with documentation.

**Comment by blakeembrey** [comment]
Fantastic, thanks :+1:

**Pull request merged**
