### PR TITLE
updating "master" branch from "dev/next"

### PR DESCRIPTION
**Pull request by Diullei**

### CODE REVIEW

**Comment by basarat** [comment]
\o/ :100:

**Comment by johnnyreilly** [comment]
:smile:

**Comment by Diullei** [comment]
:sunglasses: :thumbsup:

**Comment by nycdotnet** [comment]
Epic pull request.

**Comment by Diullei** [comment]
we are updating the 'master' branch to put it as a main branch with the latest stable stuff. The 'TSD Future' will be developed in the 'future' branch and current fixes in 'release-0.6.x'

**Pull request merged**
